<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../Common/Shared.props" />
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net461</TargetFrameworks>
    <Description>Abstractions of T-Sql objects definitions.
    </Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.ActivityMonitor.SimpleSender" Version="10.0.1-C0012-develop" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="System.Data.SqlClient" Version="4.5.0" />
  </ItemGroup>
</Project>