<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Description>Abstractions of T-Sql objects definitions.
    </Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.ActivityMonitor.SimpleSender" Version="0.0.0--052zkuh-develop" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.0" />
  </ItemGroup>
</Project>