<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Description>Abstractions of T-Sql objects definitions.
    </Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.ActivityMonitor.SimpleSender" Version="17.0.2--0003-develop" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="4.1.0" />
  </ItemGroup>
</Project>